import { Oficina, Responsavel, AgentesCidadania } from '../types';

// Dados de exemplo para Responsáveis
export const responsaveisExemplo: Responsavel[] = [
  {
    id: 'resp_1',
    nome: 'Maria Silva Santos',
    tipo: 'professor',
    email: 'maria.silva@example.com',
    telefone: '(11) 98765-4321',
    especialidade: 'Educação Física',
    dataAdmissao: '2020-03-15',
  },
  {
    id: 'resp_2',
    nome: 'João Carlos Oliveira',
    tipo: 'professor',
    email: 'joao.oliveira@example.com',
    telefone: '(11) 97654-3210',
    especialidade: 'Artes Plásticas',
    dataAdmissao: '2019-08-20',
  },
  {
    id: 'resp_3',
    nome: 'Ana Paula Costa',
    tipo: 'estagiario',
    email: 'ana.costa@example.com',
    telefone: '(11) 96543-2109',
    especialidade: 'Música',
    dataAdmissao: '2023-02-10',
  },
  {
    id: 'resp_4',
    nome: 'Carlos Eduardo Lima',
    tipo: 'professor',
    email: 'carlos.lima@example.com',
    telefone: '(11) 95432-1098',
    especialidade: 'Dança',
    dataAdmissao: '2021-06-01',
  },
  {
    id: 'resp_5',
    nome: 'Fernanda Rodrigues',
    tipo: 'estagiario',
    email: 'fernanda.rodrigues@example.com',
    telefone: '(11) 94321-0987',
    especialidade: 'Informática',
    dataAdmissao: '2024-01-15',
  },
];

// Dados de exemplo para Agentes Cidadania
export const agentesCidadaniaExemplo: AgentesCidadania[] = [
  {
    id: 'agente_1',
    matriculaId: 'matricula_1',
    nome: 'Pedro Henrique Souza',
    dataNascimento: '1995-04-12',
    cpf: '123.456.789-00',
    telefone: '(11) 99876-5432',
    endereco: 'Rua das Flores, 123 - Centro',
    dataInicio: '2022-01-10',
    status: 'ativo',
  },
  {
    id: 'agente_2',
    matriculaId: 'matricula_2',
    nome: 'Juliana Pereira Santos',
    dataNascimento: '1998-07-25',
    cpf: '234.567.890-11',
    telefone: '(11) 98765-4321',
    endereco: 'Av. Brasil, 456 - Jardim',
    dataInicio: '2022-03-15',
    status: 'ativo',
  },
  {
    id: 'agente_3',
    matriculaId: 'matricula_3',
    nome: 'Rafael Almeida Costa',
    dataNascimento: '1996-11-08',
    cpf: '345.678.901-22',
    telefone: '(11) 97654-3210',
    endereco: 'Rua do Comércio, 789 - Vila Nova',
    dataInicio: '2021-09-20',
    status: 'ativo',
  },
  {
    id: 'agente_4',
    matriculaId: 'matricula_4',
    nome: 'Camila Ferreira Lima',
    dataNascimento: '1997-02-18',
    cpf: '456.789.012-33',
    telefone: '(11) 96543-2109',
    endereco: 'Praça da Paz, 321 - Centro',
    dataInicio: '2023-05-10',
    status: 'ativo',
  },
  {
    id: 'agente_5',
    matriculaId: 'matricula_5',
    nome: 'Lucas Gabriel Martins',
    dataNascimento: '1994-09-30',
    cpf: '567.890.123-44',
    telefone: '(11) 95432-1098',
    endereco: 'Rua das Palmeiras, 654 - Parque',
    dataInicio: '2020-11-05',
    status: 'inativo',
  },
];

// Dados de exemplo para Oficinas
export const oficinasExemplo: Oficina[] = [
  {
    id: 'oficina_1',
    nome: 'Futebol Infantil',
    descricao: 'Oficina de futebol para crianças e adolescentes, desenvolvendo habilidades motoras e trabalho em equipe.',
    categoria: 'esporte',
    responsavelId: 'resp_1',
    responsavel: responsaveisExemplo[0],
    horarios: [
      {
        id: 'horario_1_1',
        diaSemana: 'segunda',
        horaInicio: '14:00',
        horaFim: '16:00',
        vagas: 20,
        alunosMatriculados: [],
      },
      {
        id: 'horario_1_2',
        diaSemana: 'quarta',
        horaInicio: '14:00',
        horaFim: '16:00',
        vagas: 20,
        alunosMatriculados: [],
      },
    ],
    idadeMinima: 7,
    idadeMaxima: 14,
    vagasTotais: 40,
    vagasDisponiveis: 40,
    dataInicio: '2026-03-01',
    dataFim: '2026-12-15',
    local: 'Quadra Poliesportiva',
    sala: 'Quadra 1',
    materiais: ['Bolas de futebol', 'Coletes', 'Cones', 'Rede de gol'],
    status: 'ativa',
    dataCriacao: new Date('2026-02-15'),
  },
  {
    id: 'oficina_2',
    nome: 'Pintura e Desenho',
    descricao: 'Desenvolvimento da criatividade através de técnicas de pintura e desenho artístico.',
    categoria: 'arte',
    responsavelId: 'resp_2',
    responsavel: responsaveisExemplo[1],
    horarios: [
      {
        id: 'horario_2_1',
        diaSemana: 'terca',
        horaInicio: '09:00',
        horaFim: '11:00',
        vagas: 15,
        alunosMatriculados: [],
      },
      {
        id: 'horario_2_2',
        diaSemana: 'quinta',
        horaInicio: '09:00',
        horaFim: '11:00',
        vagas: 15,
        alunosMatriculados: [],
      },
    ],
    idadeMinima: 6,
    idadeMaxima: 16,
    vagasTotais: 30,
    vagasDisponiveis: 30,
    dataInicio: '2026-03-01',
    dataFim: '2026-11-30',
    local: 'Sala de Artes',
    sala: 'Sala 3',
    materiais: ['Tintas', 'Pincéis', 'Telas', 'Papel Canson', 'Lápis de cor', 'Giz de cera'],
    status: 'ativa',
    dataCriacao: new Date('2026-02-10'),
  },
  {
    id: 'oficina_3',
    nome: 'Violão Iniciante',
    descricao: 'Introdução ao violão, teoria musical básica e prática de repertório popular.',
    categoria: 'musica',
    responsavelId: 'resp_3',
    responsavel: responsaveisExemplo[2],
    horarios: [
      {
        id: 'horario_3_1',
        diaSemana: 'segunda',
        horaInicio: '10:00',
        horaFim: '12:00',
        vagas: 12,
        alunosMatriculados: [],
      },
    ],
    idadeMinima: 10,
    idadeMaxima: 18,
    vagasTotais: 12,
    vagasDisponiveis: 12,
    dataInicio: '2026-03-15',
    dataFim: '2026-12-20',
    local: 'Sala de Música',
    sala: 'Sala 5',
    materiais: ['Violões', 'Apostilas', 'Estantes para partitura', 'Afinadores'],
    status: 'ativa',
    dataCriacao: new Date('2026-02-20'),
  },
  {
    id: 'oficina_4',
    nome: 'Ballet Clássico',
    descricao: 'Aulas de ballet clássico para desenvolvimento de postura, disciplina e expressão corporal.',
    categoria: 'danca',
    responsavelId: 'resp_4',
    responsavel: responsaveisExemplo[3],
    horarios: [
      {
        id: 'horario_4_1',
        diaSemana: 'terca',
        horaInicio: '15:00',
        horaFim: '17:00',
        vagas: 18,
        alunosMatriculados: [],
      },
      {
        id: 'horario_4_2',
        diaSemana: 'sexta',
        horaInicio: '15:00',
        horaFim: '17:00',
        vagas: 18,
        alunosMatriculados: [],
      },
    ],
    idadeMinima: 6,
    idadeMaxima: 14,
    vagasTotais: 36,
    vagasDisponiveis: 36,
    dataInicio: '2026-03-01',
    dataFim: '2026-12-10',
    local: 'Salão de Dança',
    sala: 'Estúdio 1',
    materiais: ['Barras de apoio', 'Espelhos', 'Aparelho de som', 'Tapetes'],
    status: 'ativa',
    dataCriacao: new Date('2026-02-12'),
  },
  {
    id: 'oficina_5',
    nome: 'Informática Básica',
    descricao: 'Introdução à informática, uso de computadores, internet e aplicativos básicos.',
    categoria: 'informatica',
    responsavelId: 'resp_5',
    responsavel: responsaveisExemplo[4],
    horarios: [
      {
        id: 'horario_5_1',
        diaSemana: 'quarta',
        horaInicio: '13:00',
        horaFim: '15:00',
        vagas: 20,
        alunosMatriculados: [],
      },
      {
        id: 'horario_5_2',
        diaSemana: 'quinta',
        horaInicio: '13:00',
        horaFim: '15:00',
        vagas: 20,
        alunosMatriculados: [],
      },
    ],
    idadeMinima: 8,
    idadeMaxima: 17,
    vagasTotais: 40,
    vagasDisponiveis: 40,
    dataInicio: '2026-03-10',
    dataFim: '2026-11-25',
    local: 'Laboratório de Informática',
    sala: 'Lab 1',
    materiais: ['Computadores', 'Material didático', 'Software educativo'],
    status: 'ativa',
    dataCriacao: new Date('2026-02-25'),
  },
  {
    id: 'oficina_6',
    nome: 'Artesanato e Reciclagem',
    descricao: 'Criação de objetos artesanais utilizando materiais recicláveis.',
    categoria: 'artesanato',
    responsavelId: 'resp_2',
    responsavel: responsaveisExemplo[1],
    horarios: [
      {
        id: 'horario_6_1',
        diaSemana: 'sexta',
        horaInicio: '09:00',
        horaFim: '11:00',
        vagas: 15,
        alunosMatriculados: [],
      },
    ],
    idadeMinima: 7,
    idadeMaxima: 15,
    vagasTotais: 15,
    vagasDisponiveis: 15,
    dataInicio: '2026-04-01',
    dataFim: '2026-12-20',
    local: 'Sala de Artes',
    sala: 'Sala 4',
    materiais: ['Tesouras', 'Cola', 'Papelão', 'Garrafas PET', 'Tintas', 'Pincéis'],
    status: 'planejada',
    dataCriacao: new Date('2026-03-01'),
  },
];

// Função helper para inicializar dados no localStorage
export const inicializarDadosExemplo = () => {
  if (typeof window !== 'undefined') {
    // Verifica se já existem dados
    const oficinasExistentes = localStorage.getItem('oficinas');
    const responsaveisExistentes = localStorage.getItem('responsaveis');
    const agentesExistentes = localStorage.getItem('agentesCidadania');

    // Só inicializa se não houver dados
    if (!oficinasExistentes) {
      localStorage.setItem('oficinas', JSON.stringify(oficinasExemplo));
    }
    if (!responsaveisExistentes) {
      localStorage.setItem('responsaveis', JSON.stringify(responsaveisExemplo));
    }
    if (!agentesExistentes) {
      localStorage.setItem('agentesCidadania', JSON.stringify(agentesCidadaniaExemplo));
    }
  }
};
