import { Matricula } from '../types';

export const matriculasExemplo: Matricula[] = [
  {
    id: 'MAT001',
    nomeCompleto: 'João Silva Santos',
    dataNascimento: '2010-05-15',
    idade: 15,
    turnoSCFV: 'tarde',
    naturalidade: 'São Paulo',
    municipio: 'São Paulo',
    uf: 'SP',
    pais: 'Brasil',
    rg: '12.345.678-9',
    rgUF: 'SP',
    dataExpedicao: '2020-01-10',
    cpf: '123.456.789-00',
    cadUnicoAluno: '12345678901',
    cadUnicoResponsavel: '98765432109',
    etnia: 'parda',
    programaSocial: 'bolsa_familia',
    quantasPessoasResidencia: 5,
    nomeMae: 'Maria Silva Santos',
    rgMae: '98.765.432-1',
    ufMae: 'SP',
    nomePai: 'José Silva',
    rgPai: '87.654.321-0',
    ufPai: 'SP',
    nomeResponsavel: 'Maria Silva Santos',
    parentesco: 'Mãe',
    endereco: 'Rua das Flores',
    numeroEndereco: '123',
    complemento: 'Apto 45',
    bairro: 'Jardim Primavera',
    postoDeSaude: 'UBS Jardim Primavera',
    telefone: '(11) 98765-4321',
    telefoneOutro: '(11) 3456-7890',
    escola: 'E.E. Prof. João Mendes',
    serie: '9º ano',
    turno: 'manha',
    possuiDeficiencia: false,
    tipoDeficiencia: 'nao_possui',
    observacoes: 'Aluno participativo e interessado nas atividades.',
    utilizaTransporte: true,
    localEmbarque: 'Praça Central',
    localDesembarque: 'Portão Principal',
    almoco: true,
    encaminhadoPor: 'Assistente Social - Maria Oliveira',
    dataEncaminhamento: '2026-02-10',
    documentos: [
      {
        id: '1',
        nomeArquivo: 'rg_joao.pdf',
        tipo: 'rg',
        arquivo: null,
        url: '',
        dataUpload: new Date('2026-02-15')
      },
      {
        id: '2',
        nomeArquivo: 'comprovante_residencia.pdf',
        tipo: 'comprovante_residencia',
        arquivo: null,
        url: '',
        dataUpload: new Date('2026-02-15')
      }
    ],
    status: 'aprovada',
    dataCadastro: new Date('2026-02-15'),
    matriculaAssinada: true,
  },
  {
    id: 'MAT002',
    nomeCompleto: 'Ana Paula Costa',
    dataNascimento: '2012-08-22',
    idade: 13,
    turnoSCFV: 'manha',
    naturalidade: 'Guarulhos',
    municipio: 'Guarulhos',
    uf: 'SP',
    pais: 'Brasil',
    rg: '23.456.789-0',
    rgUF: 'SP',
    dataExpedicao: '2022-03-15',
    cpf: '234.567.890-11',
    cadUnicoAluno: '23456789012',
    cadUnicoResponsavel: '',
    etnia: 'negra',
    programaSocial: 'bpc',
    quantasPessoasResidencia: 3,
    nomeMae: 'Paula Costa',
    rgMae: '12.345.678-0',
    ufMae: 'SP',
    nomePai: '',
    rgPai: '',
    ufPai: '',
    nomeResponsavel: 'Paula Costa',
    parentesco: 'Mãe',
    endereco: 'Avenida Brasil',
    numeroEndereco: '456',
    complemento: '',
    bairro: 'Centro',
    postoDeSaude: 'UBS Centro',
    telefone: '(11) 97654-3210',
    telefoneOutro: '',
    escola: 'E.E. Maria Aparecida',
    serie: '7º ano',
    turno: 'tarde',
    possuiDeficiencia: true,
    tipoDeficiencia: 'auditiva',
    observacoes: 'Necessita acompanhamento especializado para deficiência auditiva.',
    utilizaTransporte: false,
    localEmbarque: '',
    localDesembarque: '',
    almoco: true,
    encaminhadoPor: 'CRAS - Centro de Referência',
    dataEncaminhamento: '2026-02-12',
    documentos: [
      {
        id: '3',
        nomeArquivo: 'rg_ana.pdf',
        tipo: 'rg',
        arquivo: null,
        url: '',
        dataUpload: new Date('2026-02-16')
      }
    ],
    status: 'pendente',
    dataCadastro: new Date('2026-02-16'),
    matriculaAssinada: false,
  },
  {
    id: 'MAT003',
    nomeCompleto: 'Carlos Eduardo Oliveira',
    dataNascimento: '2011-11-30',
    idade: 14,
    turnoSCFV: 'integral',
    naturalidade: 'São Paulo',
    municipio: 'São Paulo',
    uf: 'SP',
    pais: 'Brasil',
    rg: '34.567.890-1',
    rgUF: 'SP',
    dataExpedicao: '2021-06-20',
    cpf: '345.678.901-22',
    cadUnicoAluno: '34567890123',
    cadUnicoResponsavel: '87654321098',
    etnia: 'branca',
    programaSocial: 'nao_possui',
    quantasPessoasResidencia: 4,
    nomeMae: 'Mariana Oliveira',
    rgMae: '45.678.901-2',
    ufMae: 'SP',
    nomePai: 'Eduardo Oliveira',
    rgPai: '56.789.012-3',
    ufPai: 'SP',
    nomeResponsavel: 'Mariana Oliveira',
    parentesco: 'Mãe',
    endereco: 'Rua das Acácias',
    numeroEndereco: '789',
    complemento: 'Casa 2',
    bairro: 'Vila Nova',
    postoDeSaude: 'UBS Vila Nova',
    telefone: '(11) 96543-2109',
    telefoneOutro: '(11) 2345-6789',
    escola: 'E.E. Santos Dumont',
    serie: '8º ano',
    turno: 'manha',
    possuiDeficiencia: false,
    tipoDeficiencia: 'nao_possui',
    observacoes: '',
    utilizaTransporte: true,
    localEmbarque: 'Ponto de ônibus Rua Principal',
    localDesembarque: 'Entrada da instituição',
    almoco: true,
    encaminhadoPor: 'Escola Santos Dumont',
    dataEncaminhamento: '2026-02-08',
    documentos: [],
    status: 'aguardando_documentos',
    dataCadastro: new Date('2026-02-14'),
    matriculaAssinada: false,
  },
];
